FROM centos:7

# Install git
RUN yum install git -y 

# Clone our repo using our Github access token

# install our required libraries for centos
RUN yum install epel-release -y && \
    yum install python-pip -y && \
    yum install python3 -y && \
    yum install wget -y && \
    yum install python2 && \
    yum install git -y && \
    yum install gcc -y && \
    yum install gcc-c++ -y && \
    yum install python-devel -y && \
    yum install kernel-devel -y && \
    yum install gcc-c++ pkgconfig python3-devel -y && \
    yum install nano -y && \
    yum -y install fontconfig-devel && \
    yum install make -y && \
    yum install libffi-devel -y && \
    yum install openssl-devel bzip2-devel libffi-devel -y
